export const questions = [
  {
    id: 1,
    category: "Science & Nature",
    difficulty: "easy",
    question: "What is the center of our solar system?",
    options: ["Sun", "Moon", "Mars", "Jupiter"],
    answer: "Sun",
  },
  {
    id: 2,
    category: "Science & Nature",
    difficulty: "easy",
    question: "How many legs does a spider have?",
    options: ["Six", "Eight", "Ten", "Twelve"],
    answer: "Eight",
  },
  {
    id: 3,
    category: "Science & Nature",
    difficulty: "easy",
    question: "What gas do humans need to breathe to live?",
    options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Helium"],
    answer: "Oxygen",
  },
  {
    id: 4,
    category: "Science & Nature",
    difficulty: "easy",
    question: "Which animal is known as the king of the jungle?",
    options: ["Tiger", "Elephant", "Gorilla", "Lion"],
    answer: "Lion",
  },
  {
    id: 5,
    category: "Geography",
    difficulty: "easy",
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"],
    answer: "Pacific Ocean",
  },
  {
    id: 6,
    category: "Geography",
    difficulty: "easy",
    question: "Which country is home to the Great Pyramid of Giza?",
    options: ["Mexico", "Sudan", "Egypt", "Iraq"],
    answer: "Egypt",
  },
  {
    id: 7,
    category: "Geography",
    difficulty: "easy",
    question: "What is the capital city of France?",
    options: ["Lyon", "Paris", "Berlin", "Madrid"],
    answer: "Paris",
  },
  {
    id: 8,
    category: "Geography",
    difficulty: "easy",
    question: "How many continents are there on Earth?",
    options: ["Five", "Six", "Seven", "Eight"],
    answer: "Seven",
  },
  {
    id: 9,
    category: "Pop Culture & Fun",
    difficulty: "easy",
    question: "Which popular sandbox video game lets players build with blocks?",
    options: ["Roblox", "Fortnite", "Terraria", "Minecraft"],
    answer: "Minecraft",
  },
  {
    id: 10,
    category: "Pop Culture & Fun",
    difficulty: "medium",
    question: "What color is a standard tennis ball?",
    options: ["White", "Red", "Blue", "Yellow-green"],
    answer: "Yellow-green",
  },
  {
    id: 11,
    category: "Pop Culture & Fun",
    difficulty: "easy",
    question: "Which Disney movie features a princess named Elsa?",
    options: ["Moana", "Frozen", "Tangled", "Brave"],
    answer: "Frozen",
  },
  {
    id: 12,
    category: "Pop Culture & Fun",
    difficulty: "easy",
    question: "How many players are on a standard soccer team on the field?",
    options: ["Nine", "Ten", "Twelve", "Eleven"],
    answer: "Eleven",
  },
  {
    id: 13,
    category: "Math & Logic",
    difficulty: "easy",
    question: "What is 9 plus 10?",
    options: ["18", "19", "20", "21"],
    answer: "19",
  },
  {
    id: 14,
    category: "Math & Logic",
    difficulty: "easy",
    question: "How many sides does a triangle have?",
    options: ["Two", "Three", "Four", "Five"],
    answer: "Three",
  },
  {
    id: 15,
    category: "Math & Logic",
    difficulty: "medium",
    question: "What is the square root of 64?",
    options: ["Six", "Seven", "Eight", "Nine"],
    answer: "Eight",
  },
  {
    id: 16,
    category: "Math & Logic",
    difficulty: "medium",
    question: "Which number comes next in the pattern: 2, 4, 6, 8, ...?",
    options: ["9", "11", "12", "10"],
    answer: "10",
  },
  {
    id: 17,
    category: "Science & Nature",
    difficulty: "easy",
    question: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Saturn"],
    answer: "Mars",
  },
  {
    id: 18,
    category: "Science & Nature",
    difficulty: "hard",
    question: "How many bones are in the adult human body?",
    options: ["196", "206", "216", "226"],
    answer: "206",
  },
  {
    id: 19,
    category: "Geography",
    difficulty: "hard",
    question: "What is the smallest country in the world by area?",
    options: ["Monaco", "Nauru", "Vatican City", "San Marino"],
    answer: "Vatican City",
  },
  {
    id: 20,
    category: "Pop Culture & Fun",
    difficulty: "hard",
    question: "What is Superman's home planet called?",
    options: ["Krypton", "Vulcan", "Asgard", "Tatooine"],
    answer: "Krypton",
  },
  {
    id: 21,
    category: "Math & Logic",
    difficulty: "hard",
    question: "Which number comes next in the sequence: 1, 1, 2, 3, 5, 8, ...?",
    options: ["11", "12", "13", "14"],
    answer: "13",
  },
];
