export const questions = [
  {
    id: 1,
    category: "Science & Nature",
    difficulty: "easy",
    question: "What is the center of our solar system?",
    options: [
      { A: "Sun" },
      { B: "Moon" },
      { C: "Mars" },
      { D: "Jupiter" },
    ],
    answer: "Sun",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 2,
    category: "Science & Nature",
    difficulty: "easy",
    question: "How many legs does a spider have?",
    options: [
      { A: "Six" },
      { B: "Eight" },
      { C: "Ten" },
      { D: "Twelve" },
    ],
    answer: "Eight",
    isAnswered: false,
    selectedAns: "",
  },
  // {
  //   id: 3,
  //   category: "Science & Nature",
  //   difficulty: "easy",
  //   question: "What gas do humans need to breathe to live?",
  //   options: [
  //     { A: "Carbon dioxide" },
  //     { B: "Nitrogen" },
  //     { C: "Oxygen" },
  //     { D: "Helium" },
  //   ],
  //   answer: "Oxygen",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 4,
  //   category: "Science & Nature",
  //   difficulty: "easy",
  //   question: "Which animal is known as the king of the jungle?",
  //   options: [
  //     { A: "Tiger" },
  //     { B: "Elephant" },
  //     { C: "Gorilla" },
  //     { D: "Lion" },
  //   ],
  //   answer: "Lion",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 5,
  //   category: "Geography",
  //   difficulty: "easy",
  //   question: "What is the largest ocean on Earth?",
  //   options: [
  //     { A: "Atlantic Ocean" },
  //     { B: "Pacific Ocean" },
  //     { C: "Indian Ocean" },
  //     { D: "Arctic Ocean" },
  //   ],
  //   answer: "Pacific Ocean",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 6,
  //   category: "Geography",
  //   difficulty: "easy",
  //   question: "Which country is home to the Great Pyramid of Giza?",
  //   options: [
  //     { A: "Mexico" },
  //     { B: "Sudan" },
  //     { C: "Egypt" },
  //     { D: "Iraq" },
  //   ],
  //   answer: "Egypt",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 7,
  //   category: "Geography",
  //   difficulty: "easy",
  //   question: "What is the capital city of France?",
  //   options: [
  //     { A: "Lyon" },
  //     { B: "Paris" },
  //     { C: "Berlin" },
  //     { D: "Madrid" },
  //   ],
  //   answer: "Paris",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 8,
  //   category: "Geography",
  //   difficulty: "easy",
  //   question: "How many continents are there on Earth?",
  //   options: [
  //     { A: "Five" },
  //     { B: "Six" },
  //     { C: "Seven" },
  //     { D: "Eight" },
  //   ],
  //   answer: "Seven",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 9,
  //   category: "Pop Culture & Fun",
  //   difficulty: "easy",
  //   question: "Which popular sandbox video game lets players build with blocks?",
  //   options: [
  //     { A: "Roblox" },
  //     { B: "Fortnite" },
  //     { C: "Terraria" },
  //     { D: "Minecraft" },
  //   ],
  //   answer: "Minecraft",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 10,
  //   category: "Pop Culture & Fun",
  //   difficulty: "medium",
  //   question: "What color is a standard tennis ball?",
  //   options: [
  //     { A: "White" },
  //     { B: "Red" },
  //     { C: "Blue" },
  //     { D: "Yellow-green" },
  //   ],
  //   answer: "Yellow-green",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 11,
  //   category: "Pop Culture & Fun",
  //   difficulty: "easy",
  //   question: "Which Disney movie features a princess named Elsa?",
  //   options: [
  //     { A: "Moana" },
  //     { B: "Frozen" },
  //     { C: "Tangled" },
  //     { D: "Brave" },
  //   ],
  //   answer: "Frozen",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 12,
  //   category: "Pop Culture & Fun",
  //   difficulty: "easy",
  //   question: "How many players are on a standard soccer team on the field?",
  //   options: [
  //     { A: "Nine" },
  //     { B: "Ten" },
  //     { C: "Twelve" },
  //     { D: "Eleven" },
  //   ],
  //   answer: "Eleven",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 13,
  //   category: "Math & Logic",
  //   difficulty: "easy",
  //   question: "What is 9 plus 10?",
  //   options: [
  //     { A: "18" },
  //     { B: "19" },
  //     { C: "20" },
  //     { D: "21" },
  //   ],
  //   answer: "19",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 14,
  //   category: "Math & Logic",
  //   difficulty: "easy",
  //   question: "How many sides does a triangle have?",
  //   options: [
  //     { A: "Two" },
  //     { B: "Three" },
  //     { C: "Four" },
  //     { D: "Five" },
  //   ],
  //   answer: "Three",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 15,
  //   category: "Math & Logic",
  //   difficulty: "medium",
  //   question: "What is the square root of 64?",
  //   options: [
  //     { A: "Six" },
  //     { B: "Seven" },
  //     { C: "Eight" },
  //     { D: "Nine" },
  //   ],
  //   answer: "Eight",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 16,
  //   category: "Math & Logic",
  //   difficulty: "medium",
  //   question: "Which number comes next in the pattern: 2, 4, 6, 8, ...?",
  //   options: [
  //     { A: "9" },
  //     { B: "11" },
  //     { C: "12" },
  //     { D: "10" },
  //   ],
  //   answer: "10",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 17,
  //   category: "Science & Nature",
  //   difficulty: "easy",
  //   question: "Which planet is known as the Red Planet?",
  //   options: [
  //     { A: "Earth" },
  //     { B: "Mars" },
  //     { C: "Jupiter" },
  //     { D: "Saturn" },
  //   ],
  //   answer: "Mars",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 18,
  //   category: "Science & Nature",
  //   difficulty: "hard",
  //   question: "How many bones are in the adult human body?",
  //   options: [
  //     { A: "196" },
  //     { B: "206" },
  //     { C: "216" },
  //     { D: "226" },
  //   ],
  //   answer: "206",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 19,
  //   category: "Geography",
  //   difficulty: "hard",
  //   question: "What is the smallest country in the world by area?",
  //   options: [
  //     { A: "Monaco" },
  //     { B: "Nauru" },
  //     { C: "Vatican City" },
  //     { D: "San Marino" },
  //   ],
  //   answer: "Vatican City",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 20,
  //   category: "Pop Culture & Fun",
  //   difficulty: "hard",
  //   question: "What is Superman's home planet called?",
  //   options: [
  //     { A: "Krypton" },
  //     { B: "Vulcan" },
  //     { C: "Asgard" },
  //     { D: "Tatooine" },
  //   ],
  //   answer: "Krypton",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
  // {
  //   id: 21,
  //   category: "Math & Logic",
  //   difficulty: "hard",
  //   question: "Which number comes next in the sequence: 1, 1, 2, 3, 5, 8, ...?",
  //   options: [
  //     { A: "11" },
  //     { B: "12" },
  //     { C: "13" },
  //     { D: "14" },
  //   ],
  //   answer: "13",
  //   isAnswered: false,
  //   selectedAns: "",
  // },
];
