export const questions = [
  // Easy
  {
    id: 1,
    category: "Science & Nature",
    difficulty: "easy",
    question: "What is the center of our solar system?",
    options: [
      { A: "Sun" },
      { B: "Moon" },
      { C: "Mars" },
      { D: "Jupiter" },
    ],
    answer: "Sun",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 2,
    category: "Science & Nature",
    difficulty: "easy",
    question: "Which planet is known as the Red Planet?",
    options: [
      { A: "Earth" },
      { B: "Mars" },
      { C: "Jupiter" },
      { D: "Saturn" },
    ],
    answer: "Mars",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 3,
    category: "Geography",
    difficulty: "easy",
    question: "What is the largest ocean on Earth?",
    options: [
      { A: "Atlantic Ocean" },
      { B: "Pacific Ocean" },
      { C: "Indian Ocean" },
      { D: "Arctic Ocean" },
    ],
    answer: "Pacific Ocean",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 4,
    category: "Geography",
    difficulty: "easy",
    question: "What is the capital city of France?",
    options: [
      { A: "Lyon" },
      { B: "Paris" },
      { C: "Berlin" },
      { D: "Madrid" },
    ],
    answer: "Paris",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 5,
    category: "Pop Culture & Fun",
    difficulty: "easy",
    question: "Which popular sandbox video game lets players build with blocks?",
    options: [
      { A: "Roblox" },
      { B: "Fortnite" },
      { C: "Terraria" },
      { D: "Minecraft" },
    ],
    answer: "Minecraft",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 6,
    category: "Pop Culture & Fun",
    difficulty: "easy",
    question: "Which Disney movie features a princess named Elsa?",
    options: [
      { A: "Moana" },
      { B: "Frozen" },
      { C: "Tangled" },
      { D: "Brave" },
    ],
    answer: "Frozen",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 7,
    category: "Math & Logic",
    difficulty: "easy",
    question: "What is 9 plus 10?",
    options: [
      { A: "18" },
      { B: "19" },
      { C: "20" },
      { D: "21" },
    ],
    answer: "19",
    isAnswered: false,
    selectedAns: "",
  },

  // Medium
  {
    id: 8,
    category: "Science & Nature",
    difficulty: "medium",
    question: "What is the chemical symbol for gold?",
    options: [
      { A: "Ag" },
      { B: "Au" },
      { C: "Gd" },
      { D: "Go" },
    ],
    answer: "Au",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 9,
    category: "Science & Nature",
    difficulty: "medium",
    question: "What is the chemical formula for table salt?",
    options: [
      { A: "H2O" },
      { B: "CO2" },
      { C: "NaCl" },
      { D: "O2" },
    ],
    answer: "NaCl",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 10,
    category: "Geography",
    difficulty: "medium",
    question: "What is the capital of Australia?",
    options: [
      { A: "Sydney" },
      { B: "Melbourne" },
      { C: "Canberra" },
      { D: "Perth" },
    ],
    answer: "Canberra",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 11,
    category: "Geography",
    difficulty: "medium",
    question: "Which is the largest hot desert in the world?",
    options: [
      { A: "Gobi" },
      { B: "Sahara" },
      { C: "Kalahari" },
      { D: "Arabian" },
    ],
    answer: "Sahara",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 12,
    category: "Pop Culture & Fun",
    difficulty: "medium",
    question: "What color is a standard tennis ball?",
    options: [
      { A: "White" },
      { B: "Red" },
      { C: "Blue" },
      { D: "Yellow-green" },
    ],
    answer: "Yellow-green",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 13,
    category: "Math & Logic",
    difficulty: "medium",
    question: "What is the square root of 64?",
    options: [
      { A: "Six" },
      { B: "Seven" },
      { C: "Eight" },
      { D: "Nine" },
    ],
    answer: "Eight",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 14,
    category: "Math & Logic",
    difficulty: "medium",
    question: "Which number comes next in the pattern: 2, 4, 6, 8, ...?",
    options: [
      { A: "9" },
      { B: "11" },
      { C: "12" },
      { D: "10" },
    ],
    answer: "10",
    isAnswered: false,
    selectedAns: "",
  },

  // Hard
  {
    id: 15,
    category: "Science & Nature",
    difficulty: "hard",
    question: "How many bones are in the adult human body?",
    options: [
      { A: "196" },
      { B: "206" },
      { C: "216" },
      { D: "226" },
    ],
    answer: "206",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 16,
    category: "Geography",
    difficulty: "hard",
    question: "What is the smallest country in the world by area?",
    options: [
      { A: "Monaco" },
      { B: "Nauru" },
      { C: "Vatican City" },
      { D: "San Marino" },
    ],
    answer: "Vatican City",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 17,
    category: "Geography",
    difficulty: "hard",
    question: "Which mountain range forms the boundary between Europe and Asia?",
    options: [
      { A: "Alps" },
      { B: "Andes" },
      { C: "Ural Mountains" },
      { D: "Himalayas" },
    ],
    answer: "Ural Mountains",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 18,
    category: "Pop Culture & Fun",
    difficulty: "hard",
    question: "In the Harry Potter series, what is the name of Hagrid's three-headed dog?",
    options: [
      { A: "Fluffy" },
      { B: "Fang" },
      { C: "Buckbeak" },
      { D: "Norbert" },
    ],
    answer: "Fluffy",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 19,
    category: "Math & Logic",
    difficulty: "hard",
    question: "Which number comes next in the sequence: 1, 1, 2, 3, 5, 8, ...?",
    options: [
      { A: "11" },
      { B: "12" },
      { C: "13" },
      { D: "14" },
    ],
    answer: "13",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 20,
    category: "Math & Logic",
    difficulty: "hard",
    question: "What is the sum of the interior angles of a hexagon?",
    options: [
      { A: "540\u00B0" },
      { B: "630\u00B0" },
      { C: "720\u00B0" },
      { D: "810\u00B0" },
    ],
    answer: "720\u00B0",
    isAnswered: false,
    selectedAns: "",
  },
  {
    id: 21,
    category: "Math & Logic",
    difficulty: "hard",
    question: "What is 2 raised to the power of 10?",
    options: [
      { A: "512" },
      { B: "1024" },
      { C: "2048" },
      { D: "1000" },
    ],
    answer: "1024",
    isAnswered: false,
    selectedAns: "",
  },
];
